### PR TITLE
test: actually a correct LanguagesByFilename case

### PR DESCRIPTION
**Pull request by bzz**
Added a wrong fixture in #168. This fixes a first test failure from #167

### CODE REVIEW

**Comment by bzz** [comment]
Annoying as it is, Python CI profiles started to fail with

```
      /tmp/tmpqwqr2e71.build-temp/_c_enry.c:569:10: fatal error: /home/runner/work/go-enry/go-enry/.shared/libenry.h: No such file or directory
```

despite having the dependencies fixed and without any changes on our side 😞 (and the logs of the old runs expired so it is hard to debug)

**Comment by bzz** [comment]
After 

```
pip install -r python/requirements.txt
pip install -r python/requirements.dev.txt
```

a `pip -v install -e python` produces VERY different output for the same `pip 23.2.1` locally and on CI.

**Comment by bzz** [comment]
Merging as Python CI is 🟢 😎
